<a href="https://colab.research.google.com/github/dalyszz/data-science-project/blob/main/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:
import pandas as pd
url = "https://data.cdc.gov/api/views/hfr9-rurv/rows.csv?accessType=DOWNLOAD"
df = pd.read_csv(url)
pd.set_option('display.max_columns', None)

In [90]:
df.head()

,RowId,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,DataValueTypeID,Data_Value_Type,Data_Value,Data_Value_Alt,Data_Value_Footnote_Symbol,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,StratificationCategory1,Stratification1,StratificationCategory2,Stratification2,Geolocation,ClassID,TopicID,QuestionID,LocationID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2
0,BRFSS~2015~2015~66~Q35~TOC03~AGE~SEX,2015,2015,GU,Guam,BRFSS,Overall Health,Recent activity limitations in past month,Mean number of days with activity limitations ...,Number,MEAN,Mean,5.9,5.9,NaN,NaN,3.5,8.3,Age Group,Overall,Sex,Female,POINT (144.793731 13.444304),C01,TOC03,Q35,66,AGE,AGE_OVERALL,SEX,FEMALE
1,BRFSS~2015~2015~25~Q27~TMC03~AGE~SEX,2015,2015,MA,Massachusetts,BRFSS,Mental Health,Lifetime diagnosis of depression,Percentage of older adults with a lifetime dia...,%,PRCTG,Percentage,13.0,13.0,NaN,NaN,10.3,16.2,Age Group,65 years or older,Sex,Male,POINT (-72.08269067499964 42.27687047000046),C05,TMC03,Q27,25,AGE,65PLUS,SEX,MALE
2,BRFSS~2015~2015~9002~Q43~TOC11~AGE~SEX,2015,2015,MDW,Midwest,BRFSS,Overall Health,Arthritis among older adults,Percentage of older adults ever told they have...,%,PRCTG,Percentage,32.0,32.0,NaN,NaN,30.7,33.3,Age Group,50-64 years,Sex,Male,NaN,C01,TOC11,Q43,9002,AGE,5064,SEX,MALE
3,BRFSS~2015~2015~27~Q03~TMC01~AGE~SEX,2015,2015,MN,Minnesota,BRFSS,Mental Health,Frequent mental distress,Percentage of older adults who are experiencin...,%,PRCTG,Percentage,5.8,5.8,NaN,NaN,5.0,6.7,Age Group,Overall,Sex,Male,POINT (-94.79420050299967 46.35564873600049),C05,TMC01,Q03,27,AGE,AGE_OVERALL,SEX,MALE
4,BRFSS~2015~2015~29~Q43~TOC11~AGE~OVERALL,2015,2015,MO,Missouri,BRFSS,Overall Health,Arthritis among older adults,Percentage of older adults ever told they have...,%,PRCTG,Percentage,46.8,46.8,NaN,NaN,44.9,48.8,Age Group,Overall,NaN,NaN,POINT (-92.56630005299968 38.635790776000476),C01,TOC11,Q43,29,AGE,AGE_OVERALL,OVERALL,OVERALL

In [91]:
df.columns = ([
    'Row Id','Year Start', 'Year End', 'Location Abbreviated',
    'Location Description', 'Data Source', 'Class', 'Topic', 'Question',
    'Data Value Unit', 'Data Value Type ID', 'Data Value Type',
    'Data Value', 'Data Value Alt','Data Value Footnote Symbol',
    'Data Value Footnote','Low Confidence Limit',
    'High Confidence Limit','Stratification Category 1',
    'Stratification 1', 'Stratification Category 2','Stratification 2',
    'Geolocation', 'Class ID', 'Topic ID', 'Question ID', 'Location ID',
    'Stratification Category ID1', 'Stratification ID1',
    'Stratification Category ID2', 'Stratification ID2'
])

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284142 entries, 0 to 284141
Data columns (total 31 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Row Id                       284142 non-null  object
 1   Year Start                   284142 non-null  int64
 2   Year End                     284142 non-null  int64
 3   Location Abbreviated         284142 non-null  object
 4   Location Description         284142 non-null  object
 5   Data Source                  284142 non-null  object
 6   Class                        284142 non-null  object
 7   Topic                        284142 non-null  object
 8   Question                     284142 non-null  object
 9   Data Value Unit              284142 non-null  object
 10  Data Value Type ID           284142 non-null  object
 11  Data Value Type              284142 non-null  object
 12  Data Value                   192808 non-null  float64
 13  Data Value Alt               192808 non-null  float64
 14  Data Value Footnote Symbol   109976 non-null  object
 15  Data Value Footnote          109976 non-null  object
 16  Low Confidence Limit         192597 non-null  float64
 17  High Confidence Limit        192597 non-null  float64
 18  Stratification Category 1    284142 non-null  object
 19  Stratification 1             284142 non-null  object
 20  Stratification Category 2    247269 non-null  object
 21  Stratification 2             247269 non-null  object
 22  Geolocation                  253653 non-null  object
 23  Class ID                     284142 non-null  object
 24  Topic ID                     284142 non-null  object
 25  Question ID                  284142 non-null  object
 26  Location ID                  284142 non-null  int64
 27  Stratification Category ID1  284142 non-null  object
 28  Stratification ID1           284142 non-null  object
 29  Stratification Category ID2  284142 non-null  object
 30  Stratification ID2           284142 non-null  object
dtypes: float64(4), int64(3), object(24)
memory usage: 67.2+ MB

In [93]:
df.isnull().sum()

Row Id                              0
Year Start                          0
Year End                            0
Location Abbreviated                0
Location Description                0
Data Source                         0
Class                               0
Topic                               0
Question                            0
Data Value Unit                     0
Data Value Type ID                  0
Data Value Type                     0
Data Value                      91334
Data Value Alt                  91334
Data Value Footnote Symbol     174166
Data Value Footnote            174166
Low Confidence Limit            91545
High Confidence Limit           91545
Stratification Category 1           0
Stratification 1                    0
Stratification Category 2       36873
Stratification 2                36873
Geolocation                     30489
Class ID                            0
Topic ID                            0
Question ID                         0
Location ID                         0
Stratification Category ID1         0
Stratification ID1                  0
Stratification Category ID2         0
Stratification ID2                  0
dtype: int64

In [94]:
print(df.shape)

(284142, 31)

In [95]:
(df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

Data Value Footnote Symbol     61.295409
Data Value Footnote            61.295409
Low Confidence Limit           32.218046
High Confidence Limit          32.218046
Data Value                     32.143787
Data Value Alt                 32.143787
Stratification Category 2      12.976962
Stratification 2               12.976962
Geolocation                    10.730198
Class                           0.000000
Data Source                     0.000000
Location Abbreviated            0.000000
Row Id                          0.000000
Year Start                      0.000000
Year End                        0.000000
Data Value Type                 0.000000
Question                        0.000000
Data Value Unit                 0.000000
Data Value Type ID              0.000000
Topic                           0.000000
Location Description            0.000000
Stratification Category 1       0.000000
Stratification 1                0.000000
Class ID                        0.000000
Topic ID                        0.000000
Question ID                     0.000000
Location ID                     0.000000
Stratification Category ID1     0.000000
Stratification ID1              0.000000
Stratification Category ID2     0.000000
Stratification ID2              0.000000
dtype: float64

In [96]:
columns_to_drop = [
    'Row Id',
    'Class ID',
    'Topic ID',
    'Question ID',
    'Data Value Unit',
    'Data Value Type ID',
    'Data Value Alt',
    'Data Value Footnote Symbol',
    'Location ID',
    'Stratification Category 1',
    'Stratification Category ID1',
    'Stratification ID1',
    'Stratification Category ID2',
    'Stratification ID2'
]

df = df.drop(columns=columns_to_drop)

In [97]:
print(df.columns)

Index(['Year Start', 'Year End', 'Location Abbreviated',
       'Location Description', 'Data Source', 'Class', 'Topic', 'Question',
       'Data Value Type', 'Data Value', 'Data Value Footnote',
       'Low Confidence Limit', 'High Confidence Limit', 'Stratification 1',
       'Stratification Category 2', 'Stratification 2', 'Geolocation'],
      dtype='object')

In [98]:
df.head()

,Year Start,Year End,Location Abbreviated,Location Description,Data Source,Class,Topic,Question,Data Value Type,Data Value,Data Value Footnote,Low Confidence Limit,High Confidence Limit,Stratification 1,Stratification Category 2,Stratification 2,Geolocation
0,2015,2015,GU,Guam,BRFSS,Overall Health,Recent activity limitations in past month,Mean number of days with activity limitations ...,Mean,5.9,NaN,3.5,8.3,Overall,Sex,Female,POINT (144.793731 13.444304)
1,2015,2015,MA,Massachusetts,BRFSS,Mental Health,Lifetime diagnosis of depression,Percentage of older adults with a lifetime dia...,Percentage,13.0,NaN,10.3,16.2,65 years or older,Sex,Male,POINT (-72.08269067499964 42.27687047000046)
2,2015,2015,MDW,Midwest,BRFSS,Overall Health,Arthritis among older adults,Percentage of older adults ever told they have...,Percentage,32.0,NaN,30.7,33.3,50-64 years,Sex,Male,NaN
3,2015,2015,MN,Minnesota,BRFSS,Mental Health,Frequent mental distress,Percentage of older adults who are experiencin...,Percentage,5.8,NaN,5.0,6.7,Overall,Sex,Male,POINT (-94.79420050299967 46.35564873600049)
4,2015,2015,MO,Missouri,BRFSS,Overall Health,Arthritis among older adults,Percentage of older adults ever told they have...,Percentage,46.8,NaN,44.9,48.8,Overall,NaN,NaN,POINT (-92.56630005299968 38.635790776000476)